version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - department
      - employeeservice

  department:
    build: ./Department
    ports:
      - "8081:8081"

  employeeservice:
    build: ./Employee
    ports:
      - "8082:8082"
