version: '3'

services:
  eureka-server:
    build: ./cloud-eureka-discovery-service 
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER_PORT=8083
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - department
      - employeeservice
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
      - SPRING_PROFILES_ACTIVE=docker

  department:
    build: ./Department
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
      - SPRING_PROFILES_ACTIVE=docker

  employeeservice:
    build: ./Employee
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
      - SPRING_PROFILES_ACTIVE=docker

