server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8083


spring:
  cloud:
    gateway:
      routes:
      - id: employeeservice
        uri: lb://employeeservice:8082
        predicates:
        - Path=/employee/**
      - id: department
        uri: lb://department:8081
        predicates:
        - Path=/department/**
