server:
  port: 8082
spring:
  application:
    name: employeeservice
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: DMicheli%05
    url: jdbc:sqlserver://192.168.0.51\sqlexpress:53195;databaseName=CORSO2024;encrypt=true;trustServerCertificate=true
    username: dmicheli
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  
